name: Deploy backend

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: false
          tags: valentine1907/ceres-api:pr-${{ github.event.pull_request.number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: valentine1907/ceres-api:latest

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 85.209.9.46
          username: root
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ./docker_postgress_main
            docker compose -f docker-compose.yaml pull backend
            docker compose -f docker-compose.yaml up -d backend
